<a href="https://colab.research.google.com/github/RuslanTsri/Neironian_Lab1/blob/main/%D0%9D%D0%B5%D0%B9%D1%80%D0%BE%D0%BD%D0%BA%D0%B8_%D0%9B%D0%B0%D0%B1%D0%B01_%D0%A6%D0%B8%D0%BC%D0%B1%D0%B0%D0%BB%D1%8E%D0%BA_%D0%A0%D1%83%D1%81%D0%BB%D0%B0%D0%BD(%D0%86%D0%9F%D0%97_23_4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv('/content/top-1000-trending-youtube-videos.csv')

df[df['Category']=='Music']

,rank,Video,Video views,Likes,Dislikes,Category,published
1,2,Lil Nas X - Old Town Road (Official Movie) ft....,"54,071,677","3,497,955","78,799",Music,2019
2,3,JoJo Siwa - Karma (Official Video),"34,206,747","293,563",NaN,Music,2024
3,4,Wiz Khalifa - See You Again ft. Charlie Puth [...,"6,643,904,918","44,861,602",NaN,Music,2015
5,6,JP Saxe - If the World Was Ending (Official Vi...,"76,834,495","804,353","21,195",Music,2019
6,7,David Kushner - Daylight (Official Music Video),"18,558,390","680,732",NaN,Music,2023
...,...,...,...,...,...,...,...
967,968,Male cry jury with an incredible voice,"27,566,202","55,010","1,927",Music,2011
969,970,bob marley,"23,465,084","40,072","1,023",Music,2006
974,975,Juiceee feat. Milena Ceranic - Bikini,"5,790,939","8,173","1,653",Music,2011
995,996,CALIFORNIA - MONDAY JUSTICE FEAT. SNOOP DOGG (...,"943,248","2,949",22,Music,2017
997,998,Adi Golan's Group - Teaser,"56,578",NaN,NaN,Music,2014

In [ ]:
import pandas as pd
df = pd.read_csv('/content/top-1000-trending-youtube-videos.csv')

df[df['Category']!='Music']

,rank,Video,Video views,Likes,Dislikes,Category,published
0,1,"20 Tennis shots if they were not filmed, NOBOD...","3,471,237","19,023",859,NaN,2017
4,5,伊賀の天然水強炭酸水「家族で、シュワシェア。」篇 15秒,"236,085,971",38,NaN,NaN,2021
7,8,Power Star Pawan Kalyan Special Surprise To Se...,"96,686","1,007",82,Entertainment,2018
8,9,Kulit Kamu Kulit Kering dan Sensitif? Pakai Av...,"9,605,969",6,NaN,NaN,2023
9,10,Totti with a funny penalty,"8,353,318","5,613","1,082",Sports,2007
...,...,...,...,...,...,...,...
993,994,Eagles Fan Gets Wrecked by Pole,"706,418",877,40,Film & Animation,2018
994,995,UltraTap - новости из соцсетей,"498,038",706,"1,533",People & Blogs,2017
996,997,John McEnroe's most famous outburst happened i...,"4,853,621","7,254",426,Sports,2010
998,999,Keg tapping goes horribly wrong.,"751,804","3,427",313,Entertainment,2017
999,1000,LIVE Hurricane Irma - Downtown Orlando - Ameri...,"554,438",184,8,News & Politics,2016

In [ ]:
import pandas as pd
df = pd.read_csv('/content/top-1000-trending-youtube-videos.csv')

df[df['Category'].isin(['Music', 'News & Politic'])]

,rank,Video,Video views,Likes,Dislikes,Category,published
1,2,Lil Nas X - Old Town Road (Official Movie) ft....,"54,071,677","3,497,955","78,799",Music,2019
2,3,JoJo Siwa - Karma (Official Video),"34,206,747","293,563",NaN,Music,2024
3,4,Wiz Khalifa - See You Again ft. Charlie Puth [...,"6,643,904,918","44,861,602",NaN,Music,2015
5,6,JP Saxe - If the World Was Ending (Official Vi...,"76,834,495","804,353","21,195",Music,2019
6,7,David Kushner - Daylight (Official Music Video),"18,558,390","680,732",NaN,Music,2023
...,...,...,...,...,...,...,...
967,968,Male cry jury with an incredible voice,"27,566,202","55,010","1,927",Music,2011
969,970,bob marley,"23,465,084","40,072","1,023",Music,2006
974,975,Juiceee feat. Milena Ceranic - Bikini,"5,790,939","8,173","1,653",Music,2011
995,996,CALIFORNIA - MONDAY JUSTICE FEAT. SNOOP DOGG (...,"943,248","2,949",22,Music,2017
997,998,Adi Golan's Group - Teaser,"56,578",NaN,NaN,Music,2014

In [ ]:
import pandas as pd
df = pd.read_csv('/content/top-1000-trending-youtube-videos.csv')

df[(df['published'] >= 2020) & (df['published'] <= 2024)]

,rank,Video,Video views,Likes,Dislikes,Category,published
2,3,JoJo Siwa - Karma (Official Video),"34,206,747","293,563",NaN,Music,2024
4,5,伊賀の天然水強炭酸水「家族で、シュワシェア。」篇 15秒,"236,085,971",38,NaN,NaN,2021
6,7,David Kushner - Daylight (Official Music Video),"18,558,390","680,732",NaN,Music,2023
8,9,Kulit Kamu Kulit Kering dan Sensitif? Pakai Av...,"9,605,969",6,NaN,NaN,2023
10,11,Babilala ที่ทั้งแม่และลูกชื่นชอบนั้นคืออะไร?,"8,718,326",46,NaN,NaN,2021
...,...,...,...,...,...,...,...
921,922,Whiplash,"26,339,205","125,508",NaN,Music,2024
922,923,ETA (RMX),"1,036,672","33,644",NaN,Music,2024
939,940,"Come, habla y sonríe con confianza | Corega Ch...","2,630,931",8,3,NaN,2020
940,941,Survive - Support Small Business - Facebook,"4,440,336",277,53,People & Blogs,2020
941,942,It's Time.,"1,748,740",5,10,NaN,2020

In [ ]:
import pandas as pd
df = pd.read_csv('/content/top-1000-trending-youtube-videos.csv')

df = pd.DataFrame({'Likes':df['Likes'] + '_Good'})
df.to_csv('out.csv', index=False)

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/top-1000-trending-youtube-videos.csv')
dis = np.random.uniform(low=100000, high=3000000, size=(1, 50)).flatten()
like = np.random.uniform(low=100000, high=3000000, size=(1, 50)).flatten()
df = pd.DataFrame({"dislikes": dis, "likes": like})
df.to_csv('out2.csv', index=False)

In [ ]:
import pandas as pd
import plotly.express as px

df = pd.read_csv('/content/top-1000-trending-youtube-videos.csv')

fig = px.line(df.sort_values('published'),
              x='published', y='Likes',
              color='Category',
              title="Likes Over Time")
fig.show()

In [ ]:
import pandas as pd
import plotly.express as px

df = pd.read_csv('/content/top-1000-trending-youtube-videos.csv')
part = df[df['published'].isin([2005, 2010, 2015, 2020, 2025])]
fig = px.line(part,
              x='Likes',
              y='published',
              color='Category')
fig.show()

In [ ]:
import pandas as pd
import plotly.express as px

df = pd.read_csv('/content/top-1000-trending-youtube-videos.csv')
df
fig = px.scatter_3d(df, x='Likes',
                    y='published',
                    z='Video views',
                    color='Category',
                    title="Likes vs Published Date vs Views by Category")
fig.show()

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras import layers, models

# 3D візуал залежності
df = pd.read_csv('/content/alarms.csv')
fig = px.scatter_3d(df, x='sound', y='distance', z='alarm')
fig.show()

# Підготовка датафрейму
x = df[['sound', 'distance', 'visibility']].values
y = df['alarm'].values

# Розділяємо дані на тренувальний та тестовий набори,
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Ось тут ми запускаємо нашу "качалку" нейронної мережі
model = models.Sequential([
    layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Тренуємо модель.
model.fit(X_train, y_train,
          epochs=125,
          batch_size=32,
          validation_data=(X_test, y_test))

# Оцінка моделі: ну ось ми і готові, тестуємо, що вийшло
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Тест завершено. Втрата: {loss}, Точність: {accuracy}")  # Ось тут ми виводимо результат

# Прогнозування — це як передбачити майбутнє, тільки по нашим даним
new_data = np.array([
    [0.7, 0.1, 0.7],
    [0.3, 0.7, 0.3],
    [0.4, 0.5, 0.3],
    [0.6, 0.5, 0.7],
    [0.9, 0.1, 0.9]
])

# Ось і наші прогнози — кожна точка виведе "0" або "1", чи є насправді сигнал тривоги
predictions = model.predict(new_data)
print("Прогнози:")  # Ось що буде далі
print(predictions)  # Ось і результат!