<a href="https://colab.research.google.com/github/RuslanTsri/Neironian_Lab1/blob/main/%D0%9D%D0%B5%D0%B9%D1%80%D0%BE%D0%BD%D0%BA%D0%B8_%D0%9B%D0%B0%D0%B1%D0%B01_%D0%A6%D0%B8%D0%BC%D0%B1%D0%B0%D0%BB%D1%8E%D0%BA_%D0%A0%D1%83%D1%81%D0%BB%D0%B0%D0%BD(%D0%86%D0%9F%D0%97_23_4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv('/content/top-1000-trending-youtube-videos.csv')

df[df['Category']=='Music']

,rank,Video,Video views,Likes,Dislikes,Category,published
1,2,Lil Nas X - Old Town Road (Official Movie) ft....,"54,071,677","3,497,955","78,799",Music,2019
2,3,JoJo Siwa - Karma (Official Video),"34,206,747","293,563",NaN,Music,2024
3,4,Wiz Khalifa - See You Again ft. Charlie Puth [...,"6,643,904,918","44,861,602",NaN,Music,2015
5,6,JP Saxe - If the World Was Ending (Official Vi...,"76,834,495","804,353","21,195",Music,2019
6,7,David Kushner - Daylight (Official Music Video),"18,558,390","680,732",NaN,Music,2023
...,...,...,...,...,...,...,...
967,968,Male cry jury with an incredible voice,"27,566,202","55,010","1,927",Music,2011
969,970,bob marley,"23,465,084","40,072","1,023",Music,2006
974,975,Juiceee feat. Milena Ceranic - Bikini,"5,790,939","8,173","1,653",Music,2011
995,996,CALIFORNIA - MONDAY JUSTICE FEAT. SNOOP DOGG (...,"943,248","2,949",22,Music,2017
997,998,Adi Golan's Group - Teaser,"56,578",NaN,NaN,Music,2014

In [ ]:
import pandas as pd
df = pd.read_csv('/content/top-1000-trending-youtube-videos.csv')

df[df['Category']!='Music']

,rank,Video,Video views,Likes,Dislikes,Category,published
0,1,"20 Tennis shots if they were not filmed, NOBOD...","3,471,237","19,023",859,NaN,2017
4,5,伊賀の天然水強炭酸水「家族で、シュワシェア。」篇 15秒,"236,085,971",38,NaN,NaN,2021
7,8,Power Star Pawan Kalyan Special Surprise To Se...,"96,686","1,007",82,Entertainment,2018
8,9,Kulit Kamu Kulit Kering dan Sensitif? Pakai Av...,"9,605,969",6,NaN,NaN,2023
9,10,Totti with a funny penalty,"8,353,318","5,613","1,082",Sports,2007
...,...,...,...,...,...,...,...
993,994,Eagles Fan Gets Wrecked by Pole,"706,418",877,40,Film & Animation,2018
994,995,UltraTap - новости из соцсетей,"498,038",706,"1,533",People & Blogs,2017
996,997,John McEnroe's most famous outburst happened i...,"4,853,621","7,254",426,Sports,2010
998,999,Keg tapping goes horribly wrong.,"751,804","3,427",313,Entertainment,2017
999,1000,LIVE Hurricane Irma - Downtown Orlando - Ameri...,"554,438",184,8,News & Politics,2016

In [ ]:
import pandas as pd
df = pd.read_csv('/content/top-1000-trending-youtube-videos.csv')

df[df['Category'].isin(['Music', 'News & Politic'])]

,rank,Video,Video views,Likes,Dislikes,Category,published
1,2,Lil Nas X - Old Town Road (Official Movie) ft....,"54,071,677","3,497,955","78,799",Music,2019
2,3,JoJo Siwa - Karma (Official Video),"34,206,747","293,563",NaN,Music,2024
3,4,Wiz Khalifa - See You Again ft. Charlie Puth [...,"6,643,904,918","44,861,602",NaN,Music,2015
5,6,JP Saxe - If the World Was Ending (Official Vi...,"76,834,495","804,353","21,195",Music,2019
6,7,David Kushner - Daylight (Official Music Video),"18,558,390","680,732",NaN,Music,2023
...,...,...,...,...,...,...,...
967,968,Male cry jury with an incredible voice,"27,566,202","55,010","1,927",Music,2011
969,970,bob marley,"23,465,084","40,072","1,023",Music,2006
974,975,Juiceee feat. Milena Ceranic - Bikini,"5,790,939","8,173","1,653",Music,2011
995,996,CALIFORNIA - MONDAY JUSTICE FEAT. SNOOP DOGG (...,"943,248","2,949",22,Music,2017
997,998,Adi Golan's Group - Teaser,"56,578",NaN,NaN,Music,2014

In [ ]:
import pandas as pd
df = pd.read_csv('/content/top-1000-trending-youtube-videos.csv')

df[(df['published'] >= 2020) & (df['published'] <= 2024)]

,rank,Video,Video views,Likes,Dislikes,Category,published
2,3,JoJo Siwa - Karma (Official Video),"34,206,747","293,563",NaN,Music,2024
4,5,伊賀の天然水強炭酸水「家族で、シュワシェア。」篇 15秒,"236,085,971",38,NaN,NaN,2021
6,7,David Kushner - Daylight (Official Music Video),"18,558,390","680,732",NaN,Music,2023
8,9,Kulit Kamu Kulit Kering dan Sensitif? Pakai Av...,"9,605,969",6,NaN,NaN,2023
10,11,Babilala ที่ทั้งแม่และลูกชื่นชอบนั้นคืออะไร?,"8,718,326",46,NaN,NaN,2021
...,...,...,...,...,...,...,...
921,922,Whiplash,"26,339,205","125,508",NaN,Music,2024
922,923,ETA (RMX),"1,036,672","33,644",NaN,Music,2024
939,940,"Come, habla y sonríe con confianza | Corega Ch...","2,630,931",8,3,NaN,2020
940,941,Survive - Support Small Business - Facebook,"4,440,336",277,53,People & Blogs,2020
941,942,It's Time.,"1,748,740",5,10,NaN,2020

In [ ]:
import pandas as pd
df = pd.read_csv('/content/top-1000-trending-youtube-videos.csv')

df = pd.DataFrame({'Likes':df['Likes'] + '_Good'})
df.to_csv('out.csv', index=False)

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('/content/top-1000-trending-youtube-videos.csv')
dis = np.random.uniform(low=100000, high=3000000, size=(1, 50)).flatten()
like = np.random.uniform(low=100000, high=3000000, size=(1, 50)).flatten()
df = pd.DataFrame({"dislikes": dis, "likes": like})
df.to_csv('out2.csv', index=False)

In [ ]:
import pandas as pd
import plotly.express as px

df = pd.read_csv('/content/top-1000-trending-youtube-videos.csv')

fig = px.line(df.sort_values('published'),
              x='published', y='Likes',
              color='Category',
              title="Likes Over Time")
fig.show()

In [ ]:
import pandas as pd
import plotly.express as px

df = pd.read_csv('/content/top-1000-trending-youtube-videos.csv')
part = df[df['published'].isin([2005, 2010, 2015, 2020, 2025])]
fig = px.line(part,
              x='Likes',
              y='published',
              color='Category')
fig.show()

In [ ]:
import pandas as pd
import plotly.express as px

df = pd.read_csv('/content/top-1000-trending-youtube-videos.csv')
df
fig = px.scatter_3d(df, x='Likes',
                    y='published',
                    z='Video views',
                    color='Category',
                    title="Likes vs Published Date vs Views by Category")
fig.show()

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras import layers, models

# 3D візуал залежності
df = pd.read_csv('/content/alarms.csv')
fig = px.scatter_3d(df, x='sound', y='distance', z='alarm')
fig.show()

# Підготовка датафрейму
x = df[['sound', 'distance', 'visibility']].values
y = df['alarm'].values

# Розділяємо дані на тренувальний та тестовий набори,
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Ось тут ми запускаємо нашу "качалку" нейронної мережі
model = models.Sequential([
    layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Тренуємо модель.
model.fit(X_train, y_train,
          epochs=125,
          batch_size=32,
          validation_data=(X_test, y_test))

# Оцінка моделі: ну ось ми і готові, тестуємо, що вийшло
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Тест завершено. Втрата: {loss}, Точність: {accuracy}")  # Ось тут ми виводимо результат

# Прогнозування — це як передбачити майбутнє, тільки по нашим даним
new_data = np.array([
    [0.7, 0.1, 0.7],
    [0.3, 0.7, 0.3],
    [0.4, 0.5, 0.3],
    [0.6, 0.5, 0.7],
    [0.9, 0.1, 0.9]
])

# Ось і наші прогнози — кожна точка виведе "0" або "1", чи є насправді сигнал тривоги
predictions = model.predict(new_data)
print("Прогнози:")  # Ось що буде далі
print(predictions)  # Ось і результат!

Epoch 1/125

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.0000e+00 - loss: 0.6861 - val_accuracy: 0.0000e+00 - val_loss: 0.6482
Epoch 2/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6373 - val_accuracy: 0.0000e+00 - val_loss: 0.6158
Epoch 3/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6129 - val_accuracy: 0.0000e+00 - val_loss: 0.6110
Epoch 4/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: 0.6071 - val_accuracy: 0.0000e+00 - val_loss: 0.6108
Epoch 5/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6056 - val_accuracy: 0.0000e+00 - val_loss: 0.6106
Epoch 6/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6009 - val_accuracy: 0.0000e+00 - val_loss: 0.6104
Epoch 7/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6071 - val_accuracy: 0.0000e+00 - val_loss: 0.6104
Epoch 8/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: 0.6061 - val_accuracy: 0.0000e+00 - val_loss: 0.6104
Epoch 9/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6053 - val_accuracy: 0.0000e+00 - val_loss: 0.6105
Epoch 10/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6068 - val_accuracy: 0.0000e+00 - val_loss: 0.6100
Epoch 11/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6064 - val_accuracy: 0.0000e+00 - val_loss: 0.6105
Epoch 12/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6088 - val_accuracy: 0.0000e+00 - val_loss: 0.6103
Epoch 13/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6101 - val_accuracy: 0.0000e+00 - val_loss: 0.6107
Epoch 14/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6057 - val_accuracy: 0.0000e+00 - val_loss: 0.6102
Epoch 15/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: 0.6092 - val_accuracy: 0.0000e+00 - val_loss: 0.6104
Epoch 16/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6025 - val_accuracy: 0.0000e+00 - val_loss: 0.6098
Epoch 17/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0000e+00 - loss: 0.6040 - val_accuracy: 0.0000e+00 - val_loss: 0.6099
Epoch 18/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6122 - val_accuracy: 0.0000e+00 - val_loss: 0.6099
Epoch 19/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6025 - val_accuracy: 0.0000e+00 - val_loss: 0.6098
Epoch 20/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6053 - val_accuracy: 0.0000e+00 - val_loss: 0.6095
Epoch 21/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6018 - val_accuracy: 0.0000e+00 - val_loss: 0.6105
Epoch 22/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6138 - val_accuracy: 0.0000e+00 - val_loss: 0.6095
Epoch 23/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6042 - val_accuracy: 0.0000e+00 - val_loss: 0.6096
Epoch 24/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.5987 - val_accuracy: 0.0000e+00 - val_loss: 0.6091
Epoch 25/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6088 - val_accuracy: 0.0000e+00 - val_loss: 0.6094
Epoch 26/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6131 - val_accuracy: 0.0000e+00 - val_loss: 0.6092
Epoch 27/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6067 - val_accuracy: 0.0000e+00 - val_loss: 0.6096
Epoch 28/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6087 - val_accuracy: 0.0000e+00 - val_loss: 0.6092
Epoch 29/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6098 - val_accuracy: 0.0000e+00 - val_loss: 0.6100
Epoch 30/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.5989 - val_accuracy: 0.0000e+00 - val_loss: 0.6092
Epoch 31/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6028 - val_accuracy: 0.0000e+00 - val_loss: 0.6099
Epoch 32/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0000e+00 - loss: 0.5982 - val_accuracy: 0.0000e+00 - val_loss: 0.6099
Epoch 33/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0000e+00 - loss: 0.6048 - val_accuracy: 0.0000e+00 - val_loss: 0.6096
Epoch 34/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0000e+00 - loss: 0.5941 - val_accuracy: 0.0000e+00 - val_loss: 0.6092
Epoch 35/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0000e+00 - loss: 0.6016 - val_accuracy: 0.0000e+00 - val_loss: 0.6103
Epoch 36/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: 0.5969 - val_accuracy: 0.0000e+00 - val_loss: 0.6091
Epoch 37/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6017 - val_accuracy: 0.0000e+00 - val_loss: 0.6094
Epoch 38/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6076 - val_accuracy: 0.0000e+00 - val_loss: 0.6092
Epoch 39/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6068 - val_accuracy: 0.0000e+00 - val_loss: 0.6098
Epoch 40/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6042 - val_accuracy: 0.0000e+00 - val_loss: 0.6093
Epoch 41/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6042 - val_accuracy: 0.0000e+00 - val_loss: 0.6092
Epoch 42/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.5963 - val_accuracy: 0.0000e+00 - val_loss: 0.6092
Epoch 43/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: 0.5996 - val_accuracy: 0.0000e+00 - val_loss: 0.6100
Epoch 44/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6070 - val_accuracy: 0.0000e+00 - val_loss: 0.6104
Epoch 45/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: 0.6093 - val_accuracy: 0.0000e+00 - val_loss: 0.6092
Epoch 46/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6035 - val_accuracy: 0.0000e+00 - val_loss: 0.6103
Epoch 47/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.5973 - val_accuracy: 0.0000e+00 - val_loss: 0.6092
Epoch 48/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6088 - val_accuracy: 0.0000e+00 - val_loss: 0.6111
Epoch 49/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.5978 - val_accuracy: 0.0000e+00 - val_loss: 0.6093
Epoch 50/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6036 - val_accuracy: 0.0000e+00 - val_loss: 0.6095
Epoch 51/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6016 - val_accuracy: 0.0000e+00 - val_loss: 0.6106
Epoch 52/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6030 - val_accuracy: 0.0000e+00 - val_loss: 0.6098
Epoch 53/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6087 - val_accuracy: 0.0000e+00 - val_loss: 0.6098
Epoch 54/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6079 - val_accuracy: 0.0000e+00 - val_loss: 0.6102
Epoch 55/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6068 - val_accuracy: 0.0000e+00 - val_loss: 0.6099
Epoch 56/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: 0.6062 - val_accuracy: 0.0000e+00 - val_loss: 0.6095
Epoch 57/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6072 - val_accuracy: 0.0000e+00 - val_loss: 0.6105
Epoch 58/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6076 - val_accuracy: 0.0000e+00 - val_loss: 0.6092
Epoch 59/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6040 - val_accuracy: 0.0000e+00 - val_loss: 0.6098
Epoch 60/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6015 - val_accuracy: 0.0000e+00 - val_loss: 0.6098
Epoch 61/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6051 - val_accuracy: 0.0000e+00 - val_loss: 0.6094
Epoch 62/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6034 - val_accuracy: 0.0000e+00 - val_loss: 0.6093
Epoch 63/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6085 - val_accuracy: 0.0000e+00 - val_loss: 0.6110
Epoch 64/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6032 - val_accuracy: 0.0000e+00 - val_loss: 0.6094
Epoch 65/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6040 - val_accuracy: 0.0000e+00 - val_loss: 0.6095
Epoch 66/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6028 - val_accuracy: 0.0000e+00 - val_loss: 0.6099
Epoch 67/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6068 - val_accuracy: 0.0000e+00 - val_loss: 0.6111
Epoch 68/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6024 - val_accuracy: 0.0000e+00 - val_loss: 0.6100
Epoch 69/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6015 - val_accuracy: 0.0000e+00 - val_loss: 0.6099
Epoch 70/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.5985 - val_accuracy: 0.0000e+00 - val_loss: 0.6102
Epoch 71/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6082 - val_accuracy: 0.0000e+00 - val_loss: 0.6102
Epoch 72/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6049 - val_accuracy: 0.0000e+00 - val_loss: 0.6100
Epoch 73/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6094 - val_accuracy: 0.0000e+00 - val_loss: 0.6101
Epoch 74/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0000e+00 - loss: 0.6087 - val_accuracy: 0.0000e+00 - val_loss: 0.6096
Epoch 75/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6087 - val_accuracy: 0.0000e+00 - val_loss: 0.6106
Epoch 76/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.5988 - val_accuracy: 0.0000e+00 - val_loss: 0.6099
Epoch 77/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6066 - val_accuracy: 0.0000e+00 - val_loss: 0.6100
Epoch 78/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6089 - val_accuracy: 0.0000e+00 - val_loss: 0.6096
Epoch 79/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.5984 - val_accuracy: 0.0000e+00 - val_loss: 0.6099
Epoch 80/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6034 - val_accuracy: 0.0000e+00 - val_loss: 0.6101
Epoch 81/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6061 - val_accuracy: 0.0000e+00 - val_loss: 0.6096
Epoch 82/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6039 - val_accuracy: 0.0000e+00 - val_loss: 0.6098
Epoch 83/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6028 - val_accuracy: 0.0000e+00 - val_loss: 0.6099
Epoch 84/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6085 - val_accuracy: 0.0000e+00 - val_loss: 0.6096
Epoch 85/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6050 - val_accuracy: 0.0000e+00 - val_loss: 0.6101
Epoch 86/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6060 - val_accuracy: 0.0000e+00 - val_loss: 0.6098
Epoch 87/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6036 - val_accuracy: 0.0000e+00 - val_loss: 0.6107
Epoch 88/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6056 - val_accuracy: 0.0000e+00 - val_loss: 0.6096
Epoch 89/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6128 - val_accuracy: 0.0000e+00 - val_loss: 0.6106
Epoch 90/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6077 - val_accuracy: 0.0000e+00 - val_loss: 0.6103
Epoch 91/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.5990 - val_accuracy: 0.0000e+00 - val_loss: 0.6097
Epoch 92/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6004 - val_accuracy: 0.0000e+00 - val_loss: 0.6100
Epoch 93/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6095 - val_accuracy: 0.0000e+00 - val_loss: 0.6107
Epoch 94/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.5996 - val_accuracy: 0.0000e+00 - val_loss: 0.6103
Epoch 95/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6073 - val_accuracy: 0.0000e+00 - val_loss: 0.6104
Epoch 96/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6025 - val_accuracy: 0.0000e+00 - val_loss: 0.6110
Epoch 97/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6007 - val_accuracy: 0.0000e+00 - val_loss: 0.6102
Epoch 98/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6074 - val_accuracy: 0.0000e+00 - val_loss: 0.6101
Epoch 99/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6077 - val_accuracy: 0.0000e+00 - val_loss: 0.6102
Epoch 100/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: 0.6060 - val_accuracy: 0.0000e+00 - val_loss: 0.6099
Epoch 101/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: 0.6055 - val_accuracy: 0.0000e+00 - val_loss: 0.6108
Epoch 102/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.5987 - val_accuracy: 0.0000e+00 - val_loss: 0.6103
Epoch 103/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6105 - val_accuracy: 0.0000e+00 - val_loss: 0.6100
Epoch 104/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6053 - val_accuracy: 0.0000e+00 - val_loss: 0.6112
Epoch 105/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6073 - val_accuracy: 0.0000e+00 - val_loss: 0.6101
Epoch 106/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6079 - val_accuracy: 0.0000e+00 - val_loss: 0.6098
Epoch 107/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6087 - val_accuracy: 0.0000e+00 - val_loss: 0.6125
Epoch 108/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.5999 - val_accuracy: 0.0000e+00 - val_loss: 0.6098
Epoch 109/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: 0.6028 - val_accuracy: 0.0000e+00 - val_loss: 0.6104
Epoch 110/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: 0.5987 - val_accuracy: 0.0000e+00 - val_loss: 0.6102
Epoch 111/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0000e+00 - loss: 0.5995 - val_accuracy: 0.0000e+00 - val_loss: 0.6103
Epoch 112/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0000e+00 - loss: 0.6045 - val_accuracy: 0.0000e+00 - val_loss: 0.6101
Epoch 113/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0000e+00 - loss: 0.6006 - val_accuracy: 0.0000e+00 - val_loss: 0.6106
Epoch 114/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6093 - val_accuracy: 0.0000e+00 - val_loss: 0.6102
Epoch 115/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6023 - val_accuracy: 0.0000e+00 - val_loss: 0.6102
Epoch 116/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6028 - val_accuracy: 0.0000e+00 - val_loss: 0.6103
Epoch 117/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6045 - val_accuracy: 0.0000e+00 - val_loss: 0.6107
Epoch 118/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6072 - val_accuracy: 0.0000e+00 - val_loss: 0.6100
Epoch 119/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: 0.6019 - val_accuracy: 0.0000e+00 - val_loss: 0.6106
Epoch 120/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.0000e+00 - loss: 0.6014 - val_accuracy: 0.0000e+00 - val_loss: 0.6099
Epoch 121/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6024 - val_accuracy: 0.0000e+00 - val_loss: 0.6109
Epoch 122/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: 0.6051 - val_accuracy: 0.0000e+00 - val_loss: 0.6100
Epoch 123/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6085 - val_accuracy: 0.0000e+00 - val_loss: 0.6104
Epoch 124/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6073 - val_accuracy: 0.0000e+00 - val_loss: 0.6104
Epoch 125/125
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: 0.6053 - val_accuracy: 0.0000e+00 - val_loss: 0.6107
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.0000e+00 - loss: 0.6093
Тест завершено. Втрата: 0.6107175946235657, Точність: 0.0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
Прогнози:
[[0.6232931 ]
 [0.23322007]
 [0.28428456]
 [0.6274383 ]
 [0.6196269 ]]

In [11]:
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from tensorflow.keras import layers, models

# Завантаження даних
df = pd.read_csv('/content/top-1000-trending-youtube-videos.csv')
fig = px.scatter_3d(df, x='Video views', y='Likes', z='Dislikes', color="Category")
fig.show()
# Очищення: залишаємо потрібні колонки
df = df[['Video views', 'Likes', 'Dislikes', 'published']].dropna()

# Конвертація чисел: видаляємо коми та перетворюємо в int
for col in ['Video views', 'Likes', 'Dislikes']:
    df[col] = df[col].str.replace(',', '', regex=False).astype(np.int64)

# Цільова змінна: вірусність (більше 100 млн переглядів)
df['viral'] = df['Video views'].apply(lambda x: 1 if x >= 100_000_000 else 0)

# Підготовка X та y
X = df[['Likes', 'Dislikes', 'published']].values
y = df['viral'].values

# Масштабування ознак
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Розділення на тренувальні та тестові
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Побудова моделі
model = models.Sequential([
    layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

# Компіляція
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Навчання
model.fit(X_train, y_train, epochs=100, batch_size=32, validation_data=(X_test, y_test))

# Оцінка
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Loss: {loss:.4f}, Accuracy: {accuracy:.4f}')

# Прогнози
new_samples = np.array([
    [2000000, 100000, 2022],
    [15000, 500, 2017]
])

new_samples_scaled = scaler.transform(new_samples)
predictions = model.predict(new_samples_scaled)
print("Ймовірність вірусності (у відсотках):")
for i, prob in enumerate(predictions):
    percent = prob[0] * 100
    print(f"Відео {i + 1}: {percent:.4f}%")

Epoch 1/100

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

18/18 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.9847 - loss: 0.5855 - val_accuracy: 1.0000 - val_loss: 0.4115
Epoch 2/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.9928 - loss: 0.3548 - val_accuracy: 1.0000 - val_loss: 0.2217
Epoch 3/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9923 - loss: 0.1878 - val_accuracy: 1.0000 - val_loss: 0.0952
Epoch 4/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9976 - loss: 0.0809 - val_accuracy: 1.0000 - val_loss: 0.0401
Epoch 5/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9986 - loss: 0.0381 - val_accuracy: 1.0000 - val_loss: 0.0205
Epoch 6/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9967 - loss: 0.0310 - val_accuracy: 1.0000 - val_loss: 0.0134
Epoch 7/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9982 - loss: 0.0191 - val_accuracy: 1.0000 - val_loss: 0.0095
Epoch 8/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9991 - loss: 0.0122 - val_accuracy: 1.0000 - val_loss: 0.0073
Epoch 9/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9975 - loss: 0.0157 - val_accuracy: 1.0000 - val_loss: 0.0064
Epoch 10/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9973 - loss: 0.0134 - val_accuracy: 1.0000 - val_loss: 0.0056
Epoch 11/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9977 - loss: 0.0113 - val_accuracy: 1.0000 - val_loss: 0.0048
Epoch 12/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9977 - loss: 0.0108 - val_accuracy: 1.0000 - val_loss: 0.0046
Epoch 13/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0081 - val_accuracy: 1.0000 - val_loss: 0.0043
Epoch 14/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9982 - loss: 0.0082 - val_accuracy: 1.0000 - val_loss: 0.0042
Epoch 15/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9992 - loss: 0.0057 - val_accuracy: 1.0000 - val_loss: 0.0039
Epoch 16/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9965 - loss: 0.0099 - val_accuracy: 1.0000 - val_loss: 0.0042
Epoch 17/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9986 - loss: 0.0059 - val_accuracy: 1.0000 - val_loss: 0.0040
Epoch 18/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9985 - loss: 0.0054 - val_accuracy: 1.0000 - val_loss: 0.0041
Epoch 19/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9957 - loss: 0.0089 - val_accuracy: 1.0000 - val_loss: 0.0043
Epoch 20/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9960 - loss: 0.0094 - val_accuracy: 1.0000 - val_loss: 0.0039
Epoch 21/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9973 - loss: 0.0066 - val_accuracy: 1.0000 - val_loss: 0.0041
Epoch 22/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9976 - loss: 0.0059 - val_accuracy: 1.0000 - val_loss: 0.0040
Epoch 23/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9982 - loss: 0.0042 - val_accuracy: 1.0000 - val_loss: 0.0040
Epoch 24/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9968 - loss: 0.0075 - val_accuracy: 1.0000 - val_loss: 0.0042
Epoch 25/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9969 - loss: 0.0075 - val_accuracy: 1.0000 - val_loss: 0.0042
Epoch 26/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9958 - loss: 0.0068 - val_accuracy: 1.0000 - val_loss: 0.0043
Epoch 27/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9962 - loss: 0.0070 - val_accuracy: 1.0000 - val_loss: 0.0040
Epoch 28/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9964 - loss: 0.0059 - val_accuracy: 1.0000 - val_loss: 0.0040
Epoch 29/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9913 - loss: 0.0115 - val_accuracy: 1.0000 - val_loss: 0.0042
Epoch 30/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9952 - loss: 0.0075 - val_accuracy: 1.0000 - val_loss: 0.0042
Epoch 31/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9955 - loss: 0.0070 - val_accuracy: 1.0000 - val_loss: 0.0045
Epoch 32/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9961 - loss: 0.0062 - val_accuracy: 1.0000 - val_loss: 0.0043
Epoch 33/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9981 - loss: 0.0048 - val_accuracy: 1.0000 - val_loss: 0.0035
Epoch 34/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0035 - val_accuracy: 1.0000 - val_loss: 0.0043
Epoch 35/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9916 - loss: 0.0105 - val_accuracy: 1.0000 - val_loss: 0.0043
Epoch 36/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9917 - loss: 0.0111 - val_accuracy: 1.0000 - val_loss: 0.0030
Epoch 37/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0031 - val_accuracy: 1.0000 - val_loss: 0.0036
Epoch 38/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9934 - loss: 0.0085 - val_accuracy: 1.0000 - val_loss: 0.0050
Epoch 39/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9969 - loss: 0.0055 - val_accuracy: 1.0000 - val_loss: 0.0039
Epoch 40/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9990 - loss: 0.0031 - val_accuracy: 1.0000 - val_loss: 0.0038
Epoch 41/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9961 - loss: 0.0050 - val_accuracy: 1.0000 - val_loss: 0.0051
Epoch 42/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9964 - loss: 0.0042 - val_accuracy: 1.0000 - val_loss: 0.0045
Epoch 43/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9987 - loss: 0.0034 - val_accuracy: 1.0000 - val_loss: 0.0037
Epoch 44/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9956 - loss: 0.0057 - val_accuracy: 1.0000 - val_loss: 0.0054
Epoch 45/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9926 - loss: 0.0078 - val_accuracy: 1.0000 - val_loss: 0.0048
Epoch 46/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9973 - loss: 0.0034 - val_accuracy: 1.0000 - val_loss: 0.0044
Epoch 47/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9989 - loss: 0.0023 - val_accuracy: 1.0000 - val_loss: 0.0040
Epoch 48/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9995 - loss: 0.0041 - val_accuracy: 0.9855 - val_loss: 0.0126
Epoch 49/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9960 - loss: 0.0065 - val_accuracy: 1.0000 - val_loss: 0.0075
Epoch 50/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9972 - loss: 0.0064 - val_accuracy: 1.0000 - val_loss: 0.0047
Epoch 51/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9928 - loss: 0.0078 - val_accuracy: 1.0000 - val_loss: 0.0048
Epoch 52/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9979 - loss: 0.0027 - val_accuracy: 1.0000 - val_loss: 0.0048
Epoch 53/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9989 - loss: 0.0028 - val_accuracy: 1.0000 - val_loss: 0.0042
Epoch 54/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9976 - loss: 0.0033 - val_accuracy: 1.0000 - val_loss: 0.0049
Epoch 55/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9987 - loss: 0.0030 - val_accuracy: 1.0000 - val_loss: 0.0047
Epoch 56/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9988 - loss: 0.0034 - val_accuracy: 1.0000 - val_loss: 0.0053
Epoch 57/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9993 - loss: 0.0027 - val_accuracy: 1.0000 - val_loss: 0.0052
Epoch 58/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9990 - loss: 0.0022 - val_accuracy: 1.0000 - val_loss: 0.0054
Epoch 59/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9976 - loss: 0.0037 - val_accuracy: 1.0000 - val_loss: 0.0064
Epoch 60/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9976 - loss: 0.0029 - val_accuracy: 1.0000 - val_loss: 0.0063
Epoch 61/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9995 - loss: 0.0025 - val_accuracy: 1.0000 - val_loss: 0.0051
Epoch 62/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9996 - loss: 0.0028 - val_accuracy: 1.0000 - val_loss: 0.0057
Epoch 63/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9972 - loss: 0.0032 - val_accuracy: 1.0000 - val_loss: 0.0060
Epoch 64/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9995 - loss: 0.0015 - val_accuracy: 1.0000 - val_loss: 0.0052
Epoch 65/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9996 - loss: 0.0016 - val_accuracy: 1.0000 - val_loss: 0.0059
Epoch 66/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0026 - val_accuracy: 1.0000 - val_loss: 0.0060
Epoch 67/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9988 - loss: 0.0026 - val_accuracy: 0.9928 - val_loss: 0.0068
Epoch 68/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0027 - val_accuracy: 1.0000 - val_loss: 0.0061
Epoch 69/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9986 - loss: 0.0030 - val_accuracy: 0.9928 - val_loss: 0.0061
Epoch 70/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0019 - val_accuracy: 0.9928 - val_loss: 0.0064
Epoch 71/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0040 - val_accuracy: 0.9928 - val_loss: 0.0066
Epoch 72/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0023 - val_accuracy: 0.9928 - val_loss: 0.0065
Epoch 73/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0030 - val_accuracy: 0.9928 - val_loss: 0.0067
Epoch 74/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9997 - loss: 0.0028 - val_accuracy: 1.0000 - val_loss: 0.0055
Epoch 75/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0028 - val_accuracy: 0.9928 - val_loss: 0.0072
Epoch 76/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0038 - val_accuracy: 0.9928 - val_loss: 0.0068
Epoch 77/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 1.0000 - loss: 0.0019 - val_accuracy: 0.9928 - val_loss: 0.0073
Epoch 78/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 1.0000 - loss: 0.0027 - val_accuracy: 0.9928 - val_loss: 0.0071
Epoch 79/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 1.0000 - loss: 0.0029 - val_accuracy: 0.9928 - val_loss: 0.0071
Epoch 80/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9993 - loss: 0.0020 - val_accuracy: 1.0000 - val_loss: 0.0039
Epoch 81/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9997 - loss: 5.8241e-04 - val_accuracy: 1.0000 - val_loss: 0.0049
Epoch 82/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0029 - val_accuracy: 0.9928 - val_loss: 0.0080
Epoch 83/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.9928 - val_loss: 0.0080
Epoch 84/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0023 - val_accuracy: 0.9928 - val_loss: 0.0074
Epoch 85/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0050 - val_accuracy: 0.9928 - val_loss: 0.0076
Epoch 86/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 9.0692e-04 - val_accuracy: 0.9928 - val_loss: 0.0078
Epoch 87/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0025 - val_accuracy: 0.9928 - val_loss: 0.0084
Epoch 88/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.9928 - val_loss: 0.0079
Epoch 89/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 6.8982e-04 - val_accuracy: 0.9928 - val_loss: 0.0082
Epoch 90/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0021 - val_accuracy: 0.9928 - val_loss: 0.0090
Epoch 91/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0017 - val_accuracy: 0.9928 - val_loss: 0.0078
Epoch 92/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 4.0460e-04 - val_accuracy: 0.9928 - val_loss: 0.0088
Epoch 93/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.9928 - val_loss: 0.0101
Epoch 94/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 0.9928 - val_loss: 0.0094
Epoch 95/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0026 - val_accuracy: 0.9928 - val_loss: 0.0095
Epoch 96/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.9928 - val_loss: 0.0096
Epoch 97/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 6.4092e-04 - val_accuracy: 0.9928 - val_loss: 0.0099
Epoch 98/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.9928 - val_loss: 0.0099
Epoch 99/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 5.2735e-04 - val_accuracy: 0.9928 - val_loss: 0.0098
Epoch 100/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.9928 - val_loss: 0.0107
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9919 - loss: 0.0117
Loss: 0.0107, Accuracy: 0.9928
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
Ймовірність вірусності (у відсотках):
Відео 1: 0.0000%
Відео 2: 0.0001%